---

all:
  children:
    build:
      hosts:
        localhost:
          ansible_connection: local

    staging:
      hosts:
        staging-server:
          ansible_connection: local

    production:
      hosts:
        production-server:
          ansible_connection: local
