name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: wehostasia/imagebuilder:latest

    steps:
      - uses: actions/checkout@v2

      # - name: Install SSH key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_KEY }}
      #     name: id_rsa # optional
      #     known_hosts: ${{ secrets.KNOWN_HOSTS }}
      #     config: ${{ secrets.CONFIG }} # ssh_config; optional
      #     if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Show home
        run: echo ${HOME}
      - name: WhoamI
        run: whoami

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     registry: e3partners.azurecr.io
      #     username: ${{ secrets.AZURE_REGISTRY_USER }}
      #     password: ${{ secrets.AZURE_REGISTRY_PASS }}

      - name: Create ansible vault file
        run: echo ${{ secrets.ANSIBLE_VAULT }} > /root/ansible-vault

      - name: Run build image
        run: config/deploy/build.sh
